apiVersion: apps/v1
kind: Deployment
metadata:
       name: mydeploy
spec:
   replicas: 3
   selector:
    matchLabels:
      app: dev
   template:
     metadata:
        labels:
          app: dev
        name: mynginx23
        namespace: default
     spec:
        containers:
          - image: bhanuprakashece410/nginxdemo:1
            imagePullPolicy: Always
            name: mynginx2
